let shopItemsData = [
    {
    id: "yrgigyry",
    name: "Immersion Suit",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imgDom/img1.webp",
    },
    {
    id: "yrgigygh",
    name: "Life Raft",
    price: 145,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imgDom/img2.webp",
    },
    {
    id: "yrgigyop",
    name: "Fire Extinguisher",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imgDom/img3.webp",  
    },
    {
    id: "yrgigydf",
    name: "Fire Mask",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imgDom/img4.webp",
    },
    {
        id: "rrgigydf",
        name: "EEBD",
        price: 15,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "imgDom/img5.jpg",
        },
        {
    id: "qrgigydf",
    name: "Fire Man Suit",
    price: 105,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imgDom/img6.jpg",
    },
    {
        id: "irgigydf",
        name: "Life Jacket",
        price: 65,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "imgDom/img7.jpg",
        },
        {
    id: "lrgigydf",
    name: "Life Boat",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imgDom/img8.webp",
    },
    {
        id: "hrgigydf",
        name: "Rations",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "imgDom/img9.jpg",
        },
        {
            id: "drgigydf",
            name: "Fixed C02",
            price: 250,
            desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
            img: "imgDom/img10.jpg",
            },
            {
                id: "argigydf",
                name: "Hand Flares",
                price: 85,
                desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
                img: "imgDom/img11.webp",
                },
                {
                    id: "crgigydf",
                    name: "Smoke",
                    price: 75,
                    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
                    img: "imgDom/img12.jpg",
                    },
];